services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    region: oregon
    branch: main
    rootDir: backend
